### PR TITLE
support dot and badge in nav bar items

### PR DESCRIPTION
**Pull request by joshuamoreno1**
support dot and badge in nav bar items

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/maheshmnj/navbar_router/issues/30

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing using `flutter test`

If you need help, consider pinging the maintainer @maheshmnj

[Contributor Guide]: https://github.com/maheshmnj/searchfield/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by maheshmnj** [comment]
Hello @joshuamoreno1, thank you so much for the PR, Can you please add some basic sanitary tests?

You can refer [badge tests here](https://github.com/flutter/flutter/blob/9e1c857886f07d342cf106f2cd588bcd5e031bb2/packages/flutter/test/material/badge_test.dart) 

Let me know if you need any further help

**Comment by maheshmnj** [comment]
Just noticed the tests are failing let me help you with that.

**Comment by bebaoboy** [comment]
Hello, I happen to come across this package and found out a way to cleanly integrate badges with animations into the navbar, using a 3rd party **[badges](https://pub.dev/packages/badges)** of flutter and some tweaks 😄 

I can make a PR, but I wanna ask you first @maheshmnj if it's okay for **navbar_router** have a dependency on the **badges** package (although the badges itself doesn't depend on anything else)

Thank you! Have a good day!

**Comment by maheshmnj** [comment]
Hi @bebaoboy, This feature is not implmented yet and if you are interested you are welcome to make a PR and dependency on badges sounds good to me.

**Comment by maheshmnj** [comment]
Closing this PR since there has been no update for a long time incase @joshuamoreno1 you are still interested to work on this PR please feel free to reopen and make the update.

**Pull request closed without merging**
